# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bogoncha <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/01/24 15:49:12 by bogoncha          #+#    #+#              #
#    Updated: 2019/01/24 16:14:40 by bogoncha         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_cat
SRC = cat.c
CFLAGS = -Wall -Wextra -Werror

all:
	gcc $(CFLAGS) -o $(NAME) $(SRC)

clean:
	/bin/rm -f *.0

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all
